### ISSUE TITLE
进行网络训练时，报错未定义参数

### ISSUE THREAD

**Issue by quzongshun** [wentaozhu/Hierarchical-ELM-Network#2]
Net parameters 中未定义参数"SigPara"

**Comment by quzongshun** [comment]
引用了不存在的字段 'SigPara'  我不清楚此参数的设置方法

**Comment by wentaozhu** [comment]
Thank you very much for your interest. I think you refer to alpha_1, alpha_2 in the paper http://www.jdl.ac.cn/doc/2011/2015724847265241_ijcnn2015-cameraready.pdf

The values for different datasets are shown in Table 2.

**Comment by wentaozhu** [comment]
Please refer to #1 https://github.com/wentaozhu/Hierarchical-ELM-Network/issues/1
